---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: svc-mongo
    tier: back
  name: mongo
  namespace: techshopga
spec:
  selector:
    role: db
    app: mongo
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017