apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-redis
  namespace: techshopga
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: back
      app: redis
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: redis
        role: cache
        tier: back
        version: "5.0"
    spec:
      containers:
      - image: redis:5.0
        imagePullPolicy: Always
        name: cache
        ports:
        - containerPort: 6379
          protocol: TCP