---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: svc-cassandra
    tier: back
  name: cassandra
  namespace: techshopga
spec:
  selector:
    role: db
    app: cassandra
  ports:
  - port: 9042
    protocol: TCP
    targetPort: 9042