---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: svc-catalogoga
    tier: back
  name: catalogoga
  namespace: techshopga
spec:
  selector:
    role: microservice
    app: catalogoga
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
    nodePort: 30000
  type: NodePort    