---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: svc-redis
    tier: back
  name: redis
  namespace: techshopga
spec:
  selector:
    role: cache
    app: redis
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379