apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-catalogoga
  namespace: techshopga
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: back
      app: catalogoga
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: catalogoga
        role: microservice
        tier: back
        platfform: Node.js
        version: "1.0"
    spec:
      containers:
      - image: pocga/catalogoga:[image-tag]
        imagePullPolicy: Always
        name: catalogoga
        env:
        - name: PORT
          value: "4000"
        - name: MOR_DEV
          value: "development"
        - name: MONGO_ROUTE
          value: "mongodb://mongo:27017/producto"
        - name: PORTRED
          value: "6379"
        - name: HOSTRED
          value: "redis"
        - name: MOCKP_ROUTE
          value: "http://ec2-52-206-33-92.compute-1.amazonaws.com:30001/ProductosMock/AllProductos"
        - name: MOCKC_ROUTE
          value: "http://ec2-52-206-33-92.compute-1.amazonaws.com:30001/ProductosMock/AllCategorias"
        ports:
        - containerPort: 4000
          protocol: TCP